# Generated by Django 3.2.5 on 2021-08-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.IntegerField(default=0),
        ),
    ]
