# Generated by Django 3.2.5 on 2021-07-29 07:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_auto_20210729_1117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='join',
            unique_together={('uid', 'gid')},
        ),
    ]
