# Generated by Django 3.2.5 on 2021-08-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_join_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='join_request',
            unique_together=set(),
        ),
    ]
