# Generated by Django 3.2.5 on 2021-08-06 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0004_alter_join_request_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='join',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='join_request',
            unique_together={('uid', 'gid')},
        ),
    ]
