# Generated by Django 3.2.5 on 2021-08-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-id']},
        ),
    ]
