# Generated by Django 3.2.5 on 2021-08-06 04:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0005_auto_20210806_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join_Request',
            new_name='JoinRequest',
        ),
    ]
