# Generated by Django 3.2.5 on 2021-08-05 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
    ]
