# Generated by Django 3.2.5 on 2021-08-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bid',
        ),
    ]
