# Generated by Django 3.2.5 on 2021-08-02 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_join_unique_together'),
        ('board', '0002_remove_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.group'),
            preserve_default=False,
        ),
    ]
