# Generated by Django 3.2.5 on 2021-08-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_post_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
