# Generated by Django 3.2.5 on 2021-08-04 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_uid'),
        ('board', '0004_alter_board_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='gid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
