# Generated by Django 3.2.5 on 2021-08-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_gid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
    ]
